description = "Ada Wavefile Library"
long-description = """
# Ada Wavefile Library

This crate contains Ada packages for wavefile I/O.
"""
name = "audio_wavefiles"
version = "2.0.0-rc.1"
website="https://github.com/Ada-Audio/audio_wavefiles"
licenses = ["MIT"]
authors=["Gustavo A. Hoffmann"]
maintainers = ["gusthoff@gusthoff.com"]
maintainers-logins = ["gusthoff"]
project-files = ["audio_wavefiles.gpr"]
tags = ["audio", "riff", "wavefiles"]

[origin]
commit = "10cf6888bf466d231ce26f1af462e0a6839d5cd4"
url = "git+https://github.com/Ada-Audio/audio_wavefiles.git"

